# This file generates the GitHub Actions matrix.
---
include:
  - board: nice_nano_v2
    shield: melon_v1_left
    #snippet: studio-rpc-usb-uart
    #cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: melon_v1_right
